import { auth } from './firebase';

/**
 * Fetch wrapper for the Express API (apps/web/server) — replaces the
 * httpsCallable() calls this app used when the backend was Firebase Cloud
 * Functions. Unlike the web client, this app isn't served BY Express, so it
 * needs an absolute base URL, not a same-origin relative one.
 */
const API_BASE_URL = process.env.EXPO_PUBLIC_API_BASE_URL;

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  if (!API_BASE_URL) {
    throw new Error('EXPO_PUBLIC_API_BASE_URL is not set — see apps/mobile/.env.example.');
  }
  const idToken = await auth.currentUser?.getIdToken();

  const res = await fetch(`${API_BASE_URL}${path}`, {
    ...init,
    headers: {
      'Content-Type': 'application/json',
      ...(idToken ? { Authorization: `Bearer ${idToken}` } : {}),
      ...init?.headers,
    },
  });

  if (!res.ok) {
    const body = await res.json().catch(() => ({ error: res.statusText }));
    throw new Error(body.error ?? `Request to ${path} failed (${res.status})`);
  }

  if (res.status === 204) return undefined as T;
  return res.json() as Promise<T>;
}

export const api = {
  get: <T>(path: string) => request<T>(path),
  post: <T>(path: string, body?: unknown) => request<T>(path, { method: 'POST', body: JSON.stringify(body) }),
  put: <T>(path: string, body?: unknown) => request<T>(path, { method: 'PUT', body: JSON.stringify(body) }),
  delete: <T>(path: string) => request<T>(path, { method: 'DELETE' }),
};

/**
 * POST {API_BASE_URL}/api/pairing/redeem — device-pairing handoff (added
 * 2026-08-29, replaces this app's old email/password login). Exchanges a
 * short-lived one-time code (generated by the web app's Profile screen)
 * for a Firebase custom token — no auth header needed, since the whole
 * point is signing in without one. See
 * apps/web/server/routes/pairing/index.ts for the other side of this.
 */
export async function redeemPairingCode(code: string): Promise<{ customToken: string }> {
  if (!API_BASE_URL) {
    throw new Error('EXPO_PUBLIC_API_BASE_URL is not set — see apps/mobile/.env.example.');
  }
  const res = await fetch(`${API_BASE_URL}/api/pairing/redeem`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ code }),
  });
  if (!res.ok) {
    const body = await res.json().catch(() => ({ error: res.statusText }));
    throw new Error(body.error ?? 'Request failed');
  }
  return res.json();
}
