import { signInWithCustomToken, signOut } from 'firebase/auth';
import { auth } from './firebase';

/**
 * This companion app no longer has its own email/password/Google/Apple
 * sign-in (moved 2026-08-29 — see app/pairing-code.tsx) — it only signs in
 * via a custom token exchanged from a pairing code generated by the web
 * app, and signs out like any other Firebase Auth session.
 */

export function signInWithPairingToken(customToken: string) {
  return signInWithCustomToken(auth, customToken);
}

export function logout() {
  return signOut(auth);
}
