import { StyleSheet } from 'react-native';
import { colors, radius, spacing, typography } from '../../constants/theme';

export const loginScreenStyles = StyleSheet.create({
  backLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[1],
    minHeight: 44,
    alignSelf: 'flex-start',
    marginBottom: spacing[2],
  },
  backLinkText: { ...typography.body, color: colors.inkMuted },
  subtitle: { ...typography.body, color: colors.inkMuted, marginTop: spacing[2] },
  form: { marginTop: spacing[8], gap: spacing[4] },
  passwordField: { position: 'relative' },
  passwordToggle: {
    position: 'absolute',
    right: 0,
    top: 20,
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  forgotLinkRow: { alignItems: 'flex-end', marginTop: spacing[1] },
  forgotLink: { ...typography.bodySm, color: colors.inkMuted },
  error: { ...typography.bodySm, color: colors.danger },
  divider: { flexDirection: 'row', alignItems: 'center', gap: spacing[3], marginVertical: spacing[6] },
  dividerLine: { flex: 1, height: 1, backgroundColor: colors.border },
  dividerLabel: { ...typography.caption, color: colors.inkMuted },
  socialButton: {
    width: '100%',
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing[2],
    backgroundColor: colors.paperAlt,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    borderRadius: radius.md,
    paddingHorizontal: spacing[4],
  },
  googleIcon: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: colors.ink,
    alignItems: 'center',
    justifyContent: 'center',
  },
  googleIconLabel: { fontSize: 11, fontWeight: '600', color: colors.ink, lineHeight: 13 },
  footerNote: { ...typography.bodySm, textAlign: 'center', marginTop: spacing[6] },
  footerLink: { color: colors.clay, fontWeight: '500' },
});

export const signupScreenStyles = StyleSheet.create({
  backLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[1],
    minHeight: 44,
    alignSelf: 'flex-start',
    marginBottom: spacing[2],
  },
  backLinkText: { ...typography.body, color: colors.inkMuted },
  subtitle: { ...typography.body, color: colors.inkMuted, marginTop: spacing[2] },
  form: { marginTop: spacing[8], gap: spacing[4] },
  passwordField: { position: 'relative' },
  passwordToggle: {
    position: 'absolute',
    right: 0,
    top: 20,
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  error: { ...typography.bodySm, color: colors.danger },
  divider: { flexDirection: 'row', alignItems: 'center', gap: spacing[3], marginVertical: spacing[6] },
  dividerLine: { flex: 1, height: 1, backgroundColor: colors.border },
  dividerLabel: { ...typography.caption, color: colors.inkMuted },
  socialButton: {
    width: '100%',
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing[2],
    backgroundColor: colors.paperAlt,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    borderRadius: radius.md,
    paddingHorizontal: spacing[4],
  },
  googleIcon: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: colors.ink,
    alignItems: 'center',
    justifyContent: 'center',
  },
  googleIconLabel: { fontSize: 11, fontWeight: '600', color: colors.ink, lineHeight: 13 },
  footerNote: { ...typography.bodySm, textAlign: 'center', marginTop: spacing[6] },
  footerLink: { color: colors.clay, fontWeight: '500' },
});

export const welcomeScreenStyles = StyleSheet.create({
  container: { flex: 1, minHeight: '100vh' as unknown as number, justifyContent: 'space-between' },
  top: { paddingTop: spacing[4] },
  caption: { ...typography.caption, color: colors.inkMuted },
  middle: { flex: 1, justifyContent: 'center' },
  subtitle: { ...typography.body, color: colors.inkMuted, marginTop: spacing[3] },
  bottom: { paddingBottom: spacing[8], gap: spacing[3] },
});

export const forgotPasswordScreenStyles = StyleSheet.create({
  backLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[1],
    minHeight: 44,
    alignSelf: 'flex-start',
    marginBottom: spacing[2],
  },
  backLinkText: { ...typography.body, color: colors.inkMuted },
  subtitle: { ...typography.body, color: colors.inkMuted, marginTop: spacing[2] },
  form: { marginTop: spacing[8], gap: spacing[4] },
  error: { ...typography.bodySm, color: colors.danger },
  infoNote: {
    flexDirection: 'row',
    gap: spacing[2],
    alignItems: 'flex-start',
    backgroundColor: colors.paperSunken,
    borderRadius: radius.md,
    padding: spacing[4],
    marginTop: spacing[6],
  },
  infoIcon: { marginTop: 2 },
  infoText: { ...typography.bodySm, color: colors.info, flex: 1 },
  statusPanel: {
    alignItems: 'center',
    gap: spacing[4],
    paddingTop: spacing[16],
    paddingBottom: spacing[8],
  },
  statusIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 36,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(126,143,108,0.16)',
  },
  statusBody: { ...typography.bodySm, textAlign: 'center' },
});
