import { useEffect } from 'react';
import { Stack, useRouter, useSegments } from 'expo-router';
import { AuthProvider, useAuth } from '../src/store/AuthContext';

/**
 * Root stack — trimmed 2026-08-29 to a companion app for INT-2/INT-3 only
 * (Bluetooth smart-scale + wearable HealthKit/Health Connect pairing).
 * Onboarding, the daily dashboard, planner, logging, and streak/forecast
 * all moved to the web-first Express app (apps/web) — see
 * docs/02-design/02-technical/tech-stack.md's 2026-08-29 architecture
 * change. Auth moved to web too: this app no longer has its own sign-up/
 * login — pairing-code.tsx exchanges a code generated by the web app's
 * Profile screen for a Firebase custom token instead.
 */
function RootNavigator() {
  const { user, isLoading } = useAuth();
  const router = useRouter();
  const segments = useSegments();

  // pairing-code.tsx's own handleSubmit() already navigates on a fresh
  // redemption, but that misses the case where a session persists across
  // app relaunches (Firebase Auth keeps the user signed in) — expo-router's
  // initial route is still "pairing-code" (registered first below), so
  // without this a returning, already-paired user would see the code entry
  // screen again until they backed out of it manually.
  useEffect(() => {
    if (isLoading) return;
    if (user && segments[0] !== 'device-pairing') {
      router.replace('/device-pairing');
    }
  }, [user, isLoading, segments, router]);

  return (
    <Stack screenOptions={{ headerShown: false }}>
      <Stack.Screen name="pairing-code" />
      <Stack.Screen name="device-pairing" />
    </Stack>
  );
}

export default function RootLayout() {
  return (
    <AuthProvider>
      <RootNavigator />
    </AuthProvider>
  );
}
